//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:msg:props:v1.3")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:cbr-ru:msg:props:v1.3", IsNullable=false)]
public partial class MessageInfo {
    
    private string[] toField;
    
    private string fromField;
    
    private string appMessageIDField;
    
    private string messageIDField;
    
    private string correlationMessageIDField;
    
    private int messageTypeField;
    
    private string priorityField;
    
    private string legacyTransportFileNameField;
    
    private System.DateTime createTimeField;
    
    private bool createTimeFieldSpecified;
    
    private System.DateTime sendTimeField;
    
    private bool sendTimeFieldSpecified;
    
    private System.DateTime receiveTimeField;
    
    private bool receiveTimeFieldSpecified;
    
    private System.DateTime acceptTimeField;
    
    private bool acceptTimeFieldSpecified;
    
    private bool ackRequestField;
    
    private bool ackRequestFieldSpecified;
    
    private string receivedOnExternalMediumField;
    
    private bool pDIField;
    
    private bool pDIFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("To")]
    public string[] To {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    public string From {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    public string AppMessageID {
        get {
            return this.appMessageIDField;
        }
        set {
            this.appMessageIDField = value;
        }
    }
    
    /// <remarks/>
    public string MessageID {
        get {
            return this.messageIDField;
        }
        set {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    public string CorrelationMessageID {
        get {
            return this.correlationMessageIDField;
        }
        set {
            this.correlationMessageIDField = value;
        }
    }
    
    /// <remarks/>
    public int MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    public string LegacyTransportFileName {
        get {
            return this.legacyTransportFileNameField;
        }
        set {
            this.legacyTransportFileNameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTime {
        get {
            return this.createTimeField;
        }
        set {
            this.createTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateTimeSpecified {
        get {
            return this.createTimeFieldSpecified;
        }
        set {
            this.createTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime SendTime {
        get {
            return this.sendTimeField;
        }
        set {
            this.sendTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SendTimeSpecified {
        get {
            return this.sendTimeFieldSpecified;
        }
        set {
            this.sendTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ReceiveTime {
        get {
            return this.receiveTimeField;
        }
        set {
            this.receiveTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReceiveTimeSpecified {
        get {
            return this.receiveTimeFieldSpecified;
        }
        set {
            this.receiveTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime AcceptTime {
        get {
            return this.acceptTimeField;
        }
        set {
            this.acceptTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AcceptTimeSpecified {
        get {
            return this.acceptTimeFieldSpecified;
        }
        set {
            this.acceptTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool AckRequest {
        get {
            return this.ackRequestField;
        }
        set {
            this.ackRequestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AckRequestSpecified {
        get {
            return this.ackRequestFieldSpecified;
        }
        set {
            this.ackRequestFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ReceivedOnExternalMedium {
        get {
            return this.receivedOnExternalMediumField;
        }
        set {
            this.receivedOnExternalMediumField = value;
        }
    }
    
    /// <remarks/>
    public bool PDI {
        get {
            return this.pDIField;
        }
        set {
            this.pDIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PDISpecified {
        get {
            return this.pDIFieldSpecified;
        }
        set {
            this.pDIFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:msg:props:v1.3")]
public partial class EDRefID {
    
    private string eDNoField;
    
    private System.DateTime eDDateField;
    
    private string eDAuthorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string EDNo {
        get {
            return this.eDNoField;
        }
        set {
            this.eDNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime EDDate {
        get {
            return this.eDDateField;
        }
        set {
            this.eDDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EDAuthor {
        get {
            return this.eDAuthorField;
        }
        set {
            this.eDAuthorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:msg:props:v1.3")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:cbr-ru:msg:props:v1.3", IsNullable=false)]
public partial class AcknowledgementInfo {
    
    private AcknowledgementTypeCodeType acknowledgementTypeField;
    
    private string resultCodeField;
    
    private string resultTextField;
    
    /// <remarks/>
    public AcknowledgementTypeCodeType AcknowledgementType {
        get {
            return this.acknowledgementTypeField;
        }
        set {
            this.acknowledgementTypeField = value;
        }
    }
    
    /// <remarks/>
    public string ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ResultText {
        get {
            return this.resultTextField;
        }
        set {
            this.resultTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:msg:props:v1.3")]
public enum AcknowledgementTypeCodeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:msg:props:v1.3")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:cbr-ru:msg:props:v1.3", IsNullable=false)]
public partial class SequenceInfo {
    
    private int sequenceNumberField;
    
    private System.DateTime sequenceDateField;
    
    private string sequenceUICField;
    
    /// <remarks/>
    public int SequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime SequenceDate {
        get {
            return this.sequenceDateField;
        }
        set {
            this.sequenceDateField = value;
        }
    }
    
    /// <remarks/>
    public string SequenceUIC {
        get {
            return this.sequenceUICField;
        }
        set {
            this.sequenceUICField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:msg:props:v1.3")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:cbr-ru:msg:props:v1.3", IsNullable=false)]
public partial class DocInfo {
    
    private int docFormatField;
    
    private string docTypeField;
    
    private EDRefID eDRefIDField;
    
    private string docIDField;
    
    /// <remarks/>
    public int DocFormat {
        get {
            return this.docFormatField;
        }
        set {
            this.docFormatField = value;
        }
    }
    
    /// <remarks/>
    public string DocType {
        get {
            return this.docTypeField;
        }
        set {
            this.docTypeField = value;
        }
    }
    
    /// <remarks/>
    public EDRefID EDRefID {
        get {
            return this.eDRefIDField;
        }
        set {
            this.eDRefIDField = value;
        }
    }
    
    /// <remarks/>
    public string DocID {
        get {
            return this.docIDField;
        }
        set {
            this.docIDField = value;
        }
    }
}
